name: Drugsters
version: 0.0.1
main: me.lancastersstudios.skriptloader.Drugsters
api-version: 1.21
depend: [Skript]
author: Lancasters Studios
description: Modular Skript loader with bundled script support
